[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Security-Policy = "base-uri 'self'; default-src 'self'; style-src 'self' 'unsafe-inline' pro.fontawesome.com cdnjs.cloudflare.com fonts.googleapis.com use.typekit.net cdn.giesela.app; script-src 'self' 'sha256-mp1GFUpxDEYInipGTV2RLzhzl+Px+M+pSpe1cPgQGo0=' pro.fontawesome.com cdnjs.cloudflare.com ajax.cloudflare.com use.typekit.net cdn.giesela.app; font-src 'self' pro.fontawesome.com fonts.gstatic.com cdn.giesela.app use.typekit.net fonts.typekit.net; img-src 'self' p.typekit.net cdn.giesela.app; object-src 'none'; frame-ancestors 'none'; upgrade-insecure-requests; report-uri https://thesarogroup.report-uri.com/r/d/csp/enforce; report-to default"
Expect-CT = "enforce, max-age=604800, report-uri=\"http://thesarogroup.report-uri.com/r/d/ct/reportOnly\""
Report-To = "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://thesarogroup.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"
NEL = "{\"report_to\":\"default\",\"max_age\":31536000,\"include_subdomains\":true}"
Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block; report=https://thesarogroup.report-uri.com/r/d/xss/enforce"
Vary = "Accept-Encoding"
